### ISSUE TITLE
Documentation bracket missing

### ISSUE THREAD

**Issue by dmenne** [mmrabe/hypr#1]
https://cran.r-project.org/web/packages/hypr/vignettes/hypr-regression.html

There should be () in the latex-formula for h02, ho2....

**Comment by mmrabe** [comment]
Thanks for your report, @dmenne! Which formula are you referring to exactly?

**Comment by dmenne** [comment]
All "latex-style" formulae. The code is ok. Should be 3mu1 - (mu2+mu3+mu4).

**Comment by mmrabe** [comment]
Thanks a lot. We have revised that section, which will be included in the next CRAN update.
