### ISSUE TITLE
[Feature Request] Orthogonal Filler - Centering

### ISSUE THREAD

**Issue by stfnrpplngr** [mmrabe/hypr#4]
**Is your feature request related to a problem? Please describe.**
There is no way to automatize orthogonalization and/or centering of contrast matrices.

**Describe the solution you'd like**
For the further development, it would be great to have the possibility of filling unused degrees of freedom with orthogonal filler contrasts. The `make.contrasts` function in the `gmodels` package has this feature already (see https://www.rdocumentation.org/packages/gmodels/versions/2.18.1/topics/make.contrasts).

Additionaly, it would be awesome to have an easy way for centering the contrast matrices as described in Schad et al. (2020, see https://www.sciencedirect.com/science/article/pii/S0749596X19300695).

**Additional context**
Hi @mmrabe,
I really appreciate your package.  Facing complex designs and/or mixed models, `hypr` makes contrast coding a lot easier.
Thanks for your efforts!

**Comment by mmrabe** [comment]
Thanks a lot for the feedback and your feature request, @stfnrpplngr! Those functions would certainly be a great addition to the package functionality and will be implemented for the next release.

**Comment by mmrabe** [comment]
The development version on Github now comes with `filler_contrasts()` and `centered_contrasts()`. They will be included in the next release but I would appreciate any feedback prior to pushing it to CRAN. :-) Thanks again for the suggestion, @stfnrpplngr!
