### ISSUE TITLE
Knitting Error: All input arguments must be integer.

### ISSUE THREAD

**Issue by kathschn** [mmrabe/hypr#5]
**Describe the bug**
I set up a contrast coding for linear mixed modelling using the hypr package. It worked well until I tried to knit my RMarkdown script to PDF. An error message occurred: 

_Error in gcd(as.numeric.expr_num(object[[1]]@num), as.numeric.expr_num(object[[2]]@num)) : 
  All input arguments must be integer._

However, when running the code in the RMD script, there was no error message. But after I closed RStudio and re-opened it on the next day, I got the same error message even when running the RMD script. I tried to trace back the error to find that it has something to do with my customized contrast coding and the `~0` part as an input argument in particular.

**To Reproduce**

1. R version 4.1.2 (2021-11-01)
2. Paket ‘hypr’ wurde unter R Version 4.1.3 erstellt
3. coding:

```
(hProsody <- hypr((neutral+natural+exaggerated)/3~0, neutral~natural, 
                     neutral~exaggerated, 
                     levels = c("neutral","natural","exaggerated")))
```

4. console output: 

_hypr object containing 3 null hypotheses:
Error in gcd(as.numeric.expr_num(object[[1]]@num), as.numeric.expr_num(object[[2]]@num)) : 
  All input arguments must be integer._

**Expected behavior**
I expected to get the following hypr output as I did before:

_hypr object containing 3 null hypotheses:
H0.1: 0 = (neutral + natural + exaggerated)/3  (Intercept)
H0.2: 0 = neutral - natural
H0.3: 0 = neutral - exaggerated_

_Call:
hypr(~1/3 * neutral + 1/3 * natural + 1/3 * exaggerated, ~neutral -
    natural, ~neutral - exaggerated, levels = c("neutral", "natural",
"exaggerated"))_

_Hypothesis matrix (transposed):
            [,1] [,2] [,3]
neutral     1/3    1    1
natural     1/3   -1    0
exaggerated 1/3    0   -1_

_Contrast matrix:
            [,1] [,2] [,3]
neutral        1  1/3  1/3
natural        1 -2/3  1/3
exaggerated    1  1/3 -2/3_

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge
 - Version: R version 4.1.2 (2021-11-01)

**Comment by mmrabe** [comment]
Hi @kathschn! 👋 

Thanks for the bug report. This looks somewhat similar to something I have tried to fix recently in commit 6625762dc73377a2d995a7acefd476e09a0ccc7e about 3 months ago. What version of hypr are you using? If you are not yet using v0.2.8, could you please update and check if the problem persists?

Best,
Max

**Comment by kathschn** [comment]
Dear Max,

thank you for your quick reply! Indeed, it works with the updated hypr version v.0.2.8.
I tried to update the hypr version before together with other packages, but I did not realise that it did not work out properly since hypr was already loaded in my environment. However, now it worked, so thank you very much!

Best,
Kathleen

**Comment by vasishth** [comment]
I'm closing this then.
